spring.application.name=distributed-key-value-store

server.port=9090

raft.node-id=1
raft.peer-urls.2=http://node2:9091
raft.peer-urls.3=http://node3:9092

raft.election-timeout-millis-min=1000
raft.election-timeout-millis-max=2000
raft.heartbeat-interval-millis=500
raft.election-rpc-timeout-millis=500
raft.client-request-timeout-millis=1000
